In [1]:
import torch
import numpy

In [2]:
if torch.cuda.is_available():
    print("CUDA 可用")
else:
    print("CUDA 不可用")

CUDA 不可用


---

## 相互转化

将`Tensor`转为`ndarray`

In [3]:
tensor = torch.rand(3,3)
arr = numpy.random.random((3,3))
arrFromTensor = tensor.numpy()
print(tensor)
print()
print(arrFromTensor)

tensor([[0.2360, 0.4501, 0.9686],
        [0.2720, 0.3785, 0.8486],
        [0.8707, 0.5734, 0.3031]])

[[0.23598427 0.45013797 0.9685943 ]
 [0.27204067 0.37850517 0.8485941 ]
 [0.8707189  0.5734062  0.30305195]]


尝试改变`tensor[0][0]`元素，看`arrFromTensor`是否发生变化

In [4]:
tensor[0][0] = 2
print(tensor)
print()
print(arrFromTensor)

tensor([[2.0000, 0.4501, 0.9686],
        [0.2720, 0.3785, 0.8486],
        [0.8707, 0.5734, 0.3031]])

[[2.         0.45013797 0.9685943 ]
 [0.27204067 0.37850517 0.8485941 ]
 [0.8707189  0.5734062  0.30305195]]


尝试改变`arrFromTensor[2][2]`，看`tensor`是否发生变化

In [5]:
arrFromTensor[2][2] = 6
print(tensor)
print()
print(arrFromTensor)

tensor([[2.0000, 0.4501, 0.9686],
        [0.2720, 0.3785, 0.8486],
        [0.8707, 0.5734, 6.0000]])

[[2.         0.45013797 0.9685943 ]
 [0.27204067 0.37850517 0.8485941 ]
 [0.8707189  0.5734062  6.        ]]


`Tensor`可以使用`numpy()`方法转换为`ndarray`数组

`Tensor.from_numpy()`函数可以由`ndarray`构造`Tensor`

二者在**使用这两种方式**转换时，不存在内存复制，因此速度快

但改变其中一个，另一个的数据也随之发生改变

如果需要保持数据隔离，需要使用`copy()`方法

In [6]:
arrFromTensorCopy = tensor.numpy().copy()
tensorFromArrCopy = torch.from_numpy(arr.copy())

---

## 对比索引

In [7]:
tensor = torch.tensor(([1,2],[3,4]))
arr = numpy.array([[1,2],[3,4]])
print('tensor\n',tensor)
print('-------')
print('array\n', arr)
print('-------')

tensor
 tensor([[1, 2],
        [3, 4]])
-------
array
 [[1 2]
 [3 4]]
-------


In [8]:
print('tensor')
print(tensor[:1, :1])
print('-'*10)

print('array')
print(arr[:1,:1])


tensor
tensor([[1]])
----------
array
[[1]]


In [9]:
print(tensor[1])
print(tensor[1][1])
print(tensor[1,1])
print('-'*10)

print(arr[1])
print(arr[1][1])
print(arr[1,1])

tensor([3, 4])
tensor(4)
tensor(4)
----------
[3 4]
4
4


经过对比，torch和numpy在索引的处理上表现一致：
- 当索引是一个整数值而不是一个`slice`时，切片出的数组会降维
- 均可以进行几个维度同时索引（几个索引写在一个方括号内）

---

## 对比拼接

In [10]:
t_2 = torch.tensor([[8,8],[8,8]])
a_2 = numpy.array([[8,8],[8,8]])
print(t_2)
print('-'*10)
print(a_2)

tensor([[8, 8],
        [8, 8]])
----------
[[8 8]
 [8 8]]


In [11]:
print(torch.cat((tensor, t_2)))
print('-'*10)
print(numpy.concatenate((arr,a_2)))

tensor([[1, 2],
        [3, 4],
        [8, 8],
        [8, 8]])
----------
[[1 2]
 [3 4]
 [8 8]
 [8 8]]


In [12]:
print(torch.cat((tensor, t_2), dim=1))
print('-'*10)
print(numpy.concatenate((arr,a_2), axis=1))

tensor([[1, 2, 8, 8],
        [3, 4, 8, 8]])
----------
[[1 2 8 8]
 [3 4 8 8]]


合并的行为也是一致的

默认是纵向堆叠

可以通过参数控制堆叠的方向：
- `0`是第一个维度，行 
- `1`是第二个维度，列
- 超过二维以此类推

另外，参数名不同，torch中为`dim`，表示维度；numpy中为`axis`，表示轴

---

## 对比运算

### 标量运算

In [13]:
print(tensor)
print(tensor + 2)
print(tensor * 2)
print(tensor ** 2)
print(torch.sin(tensor))
print(torch.sign(tensor))
print(torch.sigmoid(tensor))

tensor([[1, 2],
        [3, 4]])
tensor([[3, 4],
        [5, 6]])
tensor([[2, 4],
        [6, 8]])
tensor([[ 1,  4],
        [ 9, 16]])
tensor([[ 0.8415,  0.9093],
        [ 0.1411, -0.7568]])
tensor([[1, 1],
        [1, 1]])
tensor([[0.7311, 0.8808],
        [0.9526, 0.9820]])


In [14]:
print(arr)
print(arr + 2)
print(arr * 2)
print(arr ** 2)
print(numpy.sin(arr))
print(numpy.sign(arr))
print(1/(1 + numpy.exp(-arr)))

[[1 2]
 [3 4]]
[[3 4]
 [5 6]]
[[2 4]
 [6 8]]
[[ 1  4]
 [ 9 16]]
[[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]]
[[1 1]
 [1 1]]
[[0.73105858 0.88079708]
 [0.95257413 0.98201379]]


标量的行为二者基本相同

torch库中会多一些机器学习常用的函数

### 矩阵运算

In [15]:
t_2 = torch.tensor([
    [1,1],
    [0,1]
])
print(tensor * t_2)
print(tensor @ t_2)

tensor([[1, 2],
        [0, 4]])
tensor([[1, 3],
        [3, 7]])


In [16]:
a_2 = numpy.array([
    [1,1],
    [0,1]
])
print(arr * a_2)
print(arr @ a_2)

[[1 2]
 [0 4]]
[[1 3]
 [3 7]]


矩阵计算行为也相同

使用`*`表示矩阵各个元素依次相乘

使用`@`表示矩阵乘法

### 矩阵x向量

In [17]:
t_v = torch.tensor([2,2])
print(tensor @ t_v)

tensor([ 6, 14])


In [18]:
t_m = torch.tensor([[2,2]])
print(tensor @ t_m)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x2 and 1x2)

In [19]:
t_m = torch.tensor([[2,2]]).T
print(tensor @ t_m)

tensor([[ 6],
        [14]])


In [20]:
print(tensor * t_m)

tensor([[2, 4],
        [6, 8]])


In [21]:
a_v = numpy.array([2,2])
print(arr @ a_v)

[ 6 14]


In [22]:
a_m = numpy.array([[2,2]])
print(arr @ a_m)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 2)

In [23]:
a_m = numpy.array([[2,2]]).T
print(arr @ a_m)

[[ 6]
 [14]]


In [24]:
print(arr * a_m)

[[2 4]
 [6 8]]


可以看到，torch和numpy对矩阵和向量乘积的处理是相同的

numpy中存在的**广播**机制在torch里依然存在

---

## `Tensor` 特有的功能

选择计算的设备

In [25]:
newTensor = tensor.to('cpu')
print(newTensor is tensor)

True


可以记录运算过程中的导数

In [26]:
a = torch.ones(2,2, requires_grad=True)
b = torch.ones(2,2, requires_grad=True)

c = a ** 2 + b
print('c:')
print(c)
print('-'*10)

d = torch.sum(c)
d.backward()

print(a.grad)
print(b.grad)

c:
tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)
----------
tensor([[2., 2.],
        [2., 2.]])
tensor([[1., 1.],
        [1., 1.]])


---